# Generated by Django 2.0.7 on 2021-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
