# Generated by Django 2.0.7 on 2021-02-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('coats', 'c'), ('jeans', 'j'), ('shirts', 's'), ('sweats', 's')], default='', help_text='Clothing Category', max_length=200),
        ),
    ]
