# Generated by Django 2.0.7 on 2021-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0003_auto_20210206_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('coats', 'coats'), ('jeans', 'jeans'), ('shirts', 'shirts'), ('sweats', 'sweats')], default='', help_text='Clothing Category', max_length=200),
        ),
    ]
